project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - api.qmd

execute:
  freeze: auto  # Re-render only when source changes

description-meta: "Document the EUROCONTROL Data app"

website:
  title: "EUROCONTROL Data app"
  favicon: "/media/favicon.png"
  navbar:
    background: light
    search: false
    title: false
    logo-href: "https://eurocontrol.int"
    logo: "media/EUROCONTROL-logo-standard-rgb.svg"
    left:
      - href: index.qmd
        text: App
      - href: api.qmd
        text: API

format:
  html:
    theme: cosmo
    css: media/styles.css
